# 第八章B：NumPy基础
___

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- 广播broadcasting
- 逻辑运算
- 数组高级操作
- 文件输入输出
- 随堂小项目：用Numpy实现Softmax

## 1. Numpy简介

- [numpy](http://www.numpy.org/)是Python的一个包
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，其核心代码由C语言写成
- Pandas也是基于Numpy构建的一个包
- 流行的机器学习框架（Tensorflow/PyTorch等），语法都与Numpy比较接近

首先导入`numpy` 模块:

In [ ]:
import numpy as np

## 2. 数组Array

通常我们把1维数组看作向量（vector），2维数组看做矩阵（matrix），3维以上数组看做张量（tensor）...

### 2.1 数组的初始化和访问、修改

- 我们可以用`np.array()`从list初始化一个数组:

In [ ]:
a = np.array([1, 2, 3])
print(a)

In [ ]:
print(type(a))

In [ ]:
print(a.shape)

In [ ]:
type([1,2,3])

- 可以对数组的元素进行操作（访问和赋值）

In [ ]:
a[2]

In [ ]:
a[0] = 5

In [ ]:
print(a)

- 这是二维数组-矩阵

In [ ]:
a = [[1,2,3],[2,3,4]]
b = np.array(a)
print(b)

In [ ]:
print(type(b))

In [ ]:
print(b.shape)

In [ ]:
print(b[0,2])

### 2.2 创建数组的内置函数

有一些内置的创建数组的函数:
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eyes()`
- `np.empty()`

In [ ]:
a = np.zeros((2,3))
print(a)

In [ ]:
b = np.ones((1,2))
print(b)

In [ ]:
c = np.full((2,2), 8)
print(c)

In [ ]:
d = np.eye(3)
print(d)

In [ ]:
f = np.empty((2,3,4))
print(f)

In [ ]:
print(f.shape)

- 还有用`np.random`模块构建随机数的方法：
   * `np.random.rand()`
   * `np.random.randint()`
   * `np.random.randn()`
   * `np.random.random()`
   * ...

In [ ]:
e = np.random.random((3,2))
print(e)

- 常用的还有类似于`range`的函数`np.arange()`：

In [ ]:
g = np.arange(15)
print(g)

In [ ]:
print(g.shape)

### 2.3 数组的数据类型

数组可以有不同的数据类型：

In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)

In [ ]:
print(arr)

In [ ]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

In [ ]:
print(arr)

In [ ]:
arr = np.array([1,2,3], dtype=np.int64)
print(arr.dtype)

- 生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

- 使用`astype`复制数组并转换数据类型

In [ ]:
int_arr = np.array([1,2,3,4,5])
print(int_arr, int_arr.dtype)

In [ ]:
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

- 使用`astype`将`float`转换为`int`时小数部分被舍弃

In [ ]:
float_arr = np.array([3.5,2.3,4.8,-2.2])
print(float_arr)

In [ ]:
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)

- 使用`astype`把字符串数组转换为其他类型的数组，如果失败抛出异常。

In [ ]:
str_arr = np.array(['1.24', '2.2', '5.8', '0x12ab'], dtype=np.string_)
str_arr

In [ ]:
float_arr = str_arr.astype(dtype=np.float)
print(float_arr)

- `astype`可以使用其它数组的数据类型作为参数

In [ ]:
int_arr = np.arange(10)
float_arr = np.array([2.3,4.6,9.8])
print(float_arr.dtype, int_arr.dtype)

In [ ]:
int_arr.astype(dtype=float_arr.dtype)

### 2.4 数组取值和赋值Array indexing

Numpy提供了多种取值方式.

- 创建3x4的2维数组/矩阵

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)

- 可以像list一样切片（多维数组可以从各个维度同时切片）:

In [ ]:
b = a[0:2,2:4].copy()
print(b)

- 然后可以修改切片出来的对象，然后完成对原数组的赋值.

In [ ]:
b[0,0] = 111111
print(b)
print(a)

- 可以通过行列的索引获取你想要的部分数据:

In [ ]:
row_r1 = a[1,:]
print(row_r1, row_r1.shape)

In [ ]:
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

In [ ]:
row_r3 = a[[1], :]
print(row_r3, row_r3.shape)

在第2个维度上切片也可以:

In [ ]:
a

In [ ]:
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

In [ ]:
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)

- 还可以自由地行列组合进行取值:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

In [ ]:
print(a[[0,1,2], [0,1,0]])
print(a[[0,1,2], [0,1,0]].shape)

In [ ]:
print(np.array([a[0,0], a[1,1], a[2,0]]))

In [ ]:
print(a)
print(a[[0,0], [1,0]])
print(np.array([a[0,0], a[0,1]]))

- 更多的时候，我们需要用条件判定取值:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

In [ ]:
bool_index = (a > 2)
print(bool_index)

- 用这个布尔数组作为下标就可以获取符合条件的元素

In [ ]:
print(a[bool_index].shape)

In [ ]:
print(a[bool_index])

- 将几个操作合并到一起：

In [ ]:
print(a[a>2])

## 3. 数学运算

下面这些运算在科学运算中经常经常会用到的。

### 3.1 逐个元素的运算

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
print(x)
print(y)

In [ ]:
print(x.shape)
print(y.shape)

- 逐个元素求和有下面2种方式
  * 用`<arr> + <arr>`
  * 用`np.add()`函数

In [ ]:
x+y

In [ ]:
np.add(x,y)

- 还有逐个元素算差

In [ ]:
x-y

In [ ]:
np.subtract(x,y)

- 逐元素相乘

In [ ]:
x*y

In [ ]:
np.multiply(x,y)

- 逐元素相除

In [ ]:
x/y

In [ ]:
np.divide(x, y)

- 逐个元素求平方根：

In [ ]:
np.sqrt(x)

### 3.2 矩阵的乘法

- 那矩阵的乘法运算怎么办？可以参考[matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html)

我们可以构造两个向量，求向量的内积也有两种方式：
- `<v1>.dot(<v2>)`
- `np.dot(<v1>, <v2>)`

In [ ]:
v = np.array([9,10])
w = np.array([10,11])
print(v.shape)

In [ ]:
v.dot(w)

In [ ]:
np.dot(v,w)

- 对于矩阵之间的乘法

In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x)
print()
print(y)

In [ ]:
v

In [ ]:
print(x.dot(v))

In [ ]:
np.dot(x, v)

In [ ]:
x.dot(y)

In [ ]:
np.dot(x,y)

- 矩阵的转置简单粗暴

In [ ]:
x

In [ ]:
x.T

- 一维的vector转置还是自己

In [ ]:
v.shape

In [ ]:
v.T.shape

- 二维的就不一样了

In [ ]:
w = np.array([[1,2,3]])
print(w, w.shape)

In [ ]:
print(w.T)

- 利用转置矩阵可以计算内积

In [ ]:
arr = np.random.randn(6,3)
arr

In [ ]:
print(arr.T.dot(arr))

In [ ]:
print(np.dot(arr.T,arr))

- 高维的tensor也可以转置

In [ ]:
arr = np.arange(16).reshape(2,2,4)
print(arr, arr.shape)

In [ ]:
print(arr.transpose((1,0,2)))

In [ ]:
print(arr.transpose((0,2,1)))

In [ ]:
print(arr.transpose((2,1,0)))

In [ ]:
print(arr.swapaxes(1,2))

In [ ]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(x)
print()
print(y)

In [ ]:
print(np.matmul(x,y).shape)

In [ ]:
print(np.dot(x,y).shape)

In [ ]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(16).reshape(2,4,2)
print(x.dot(y).shape)

In [ ]:
np.matmul(x,y).shape

- 科学运算常用到的矩阵内元素的运算是求和，用 `np.sum()`就可以完成:

In [ ]:
x= np.array([[1,2], [3,4]])
print(x)

In [ ]:
print(np.sum(x))
print(x.sum())

In [ ]:
print(np.sum(x, axis=0))

In [ ]:
print(np.sum(x, axis=1))

In [ ]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

- 还有一些运算，如求和，求平均，求累和，累积都可以用`numpy`实现

In [ ]:
print(x.cumsum(axis=0))
print(x.cumsum(axis=1))

In [ ]:
print(x.cumprod(axis=0))
print(x.cumprod(axis=1))

以上是最基本的运算，更多的运算可能得查查相关[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### 3.3 其他基本运算

- 比如一维数组的排序：

In [ ]:
arr = np.random.randn(8) * 10
print(arr)

In [ ]:
arr.sort()
print(arr)

- 二维数组也可以在某些维度上排序

In [ ]:
arr = np.random.randn(5,3) * 10
print(arr)

In [ ]:
arr.sort(1)
print(arr)

- 我们可以很容易找出排序后位置在5%的数字

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05 * len(large_arr))])

### 3.4 广播Broadcasting

> 当一个小矩阵去与大矩阵进行运算的时候，我们希望小矩阵能循环和大矩阵的块进行相同的计算，这就需要用到广播了。

- 比如，给矩阵x的每一行都逐元素加上一个向量，然后生成y

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print()
print(v)

In [ ]:
y = np.empty_like(x)
print(y)

- 一种比较简暴的方式是，用for循环逐个相加

In [ ]:
for i in range(4):
    y[i,:] = x[i,:] + v    
print(y)

- 这种方法当然可以，问题是效率低下，尤其是当x矩阵的行数非常多的情况。

> Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

- 正因为broadcasting机制的存在，上面的操作可以简化为一个简单的求和操作：

In [ ]:
print(x.shape, v.shape)
x + v

当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，如果两arrays兼容，则输出broadcasting结果：

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):          3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):     1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [ ]:
v = np.array([1,2,3])
w = np.array([4,5])
print(v.shape, w.shape)

In [ ]:
v = v.reshape(3,1)
print(v.shape)

In [ ]:
v

In [ ]:
w

In [ ]:
v + w

那如果要把一个矩阵的每一行都加上一个向量呢

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
print(x + v)

In [ ]:

x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5]) # 2

In [ ]:
(x.T + w).T

上面那个操作太复杂了，其实我们可以直接这么做嘛

In [ ]:
x + np.reshape(w, (2,1))

broadcasting当然可以逐元素运算了

总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

### 3.5 逻辑运算

In [ ]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [ ]:
cond = np.array([True, False, True, True, False])

In [ ]:
print(np.where(cond, x_arr, y_arr))

In [ ]:
arr = np.random.randn(4,4)
print(arr)

In [ ]:
arr > 0

In [ ]:
print(np.where(arr > 0, 1,-1))

In [ ]:
print(np.where(arr > 0, 1,arr))

## 4. 进阶ndarray操作

### 4.1 用reshape来改变tensor的维度

numpy可以很容易地把一维数组转成二维数组，三维数组。

In [187]:
arr = np.arange(8)
print(arr.shape)

(8,)


In [188]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [189]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [190]:
arr = np.arange(15)
print(arr.reshape(5,3).shape)

(5, 3)


如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度

In [191]:
print(arr.reshape(5,-1).shape)

(5, 3)


还可以从其他的ndarray中获取shape信息然后reshape

In [192]:
other_arr = np.ones((3,5))
print(other_arr.shape) # tuple

(3, 5)


In [193]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用ravel来拉平为一个向量（一维数组）

In [194]:
arr = arr.reshape(other_arr.shape)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [195]:
arr.ravel().shape

(15,)

### 4.2 连接两个二维数组

In [196]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1, "\n\n", arr2)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]]


In [197]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [198]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- 还有所谓的堆叠（stack）。堆叠是连接的另一种表述
- 堆叠还可以分为垂直stack与水平stack

In [199]:
np.vstack((arr1, arr2)) # vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [200]:
np.hstack((arr1, arr2)) # horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- 还可以拆分数组

In [201]:
arr = np.random.rand(5,5)
print(arr)

[[7.47767465e-01 7.61656891e-01 1.77975614e-01 2.85834957e-01
  4.18278325e-01]
 [5.81177734e-01 8.15406212e-01 5.08022296e-02 9.91677121e-01
  9.69858837e-02]
 [8.36898144e-01 8.53900010e-04 9.70627262e-01 2.77977728e-01
  7.99307683e-01]
 [8.46856331e-01 2.91860237e-01 3.32379624e-01 8.95367630e-01
  1.22423513e-01]
 [3.87198881e-02 1.96190392e-01 1.44468315e-01 9.87295798e-01
  6.01238584e-01]]


In [202]:
first, second, third = np.split(arr, [1,3], axis=0)
print(first, '\n\n', second, '\n\n', third)

[[0.74776746 0.76165689 0.17797561 0.28583496 0.41827833]] 

 [[5.81177734e-01 8.15406212e-01 5.08022296e-02 9.91677121e-01
  9.69858837e-02]
 [8.36898144e-01 8.53900010e-04 9.70627262e-01 2.77977728e-01
  7.99307683e-01]] 

 [[0.84685633 0.29186024 0.33237962 0.89536763 0.12242351]
 [0.03871989 0.19619039 0.14446831 0.9872958  0.60123858]]


- 堆叠辅助

In [203]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
[[-0.76291597  0.80553492]
 [ 0.21346033  0.55389701]
 [ 0.96813748  0.83773147]]


- 还可以用`np.r_()`按行堆叠

In [204]:
print(np.r_[arr1, arr2])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [-0.76291597  0.80553492]
 [ 0.21346033  0.55389701]
 [ 0.96813748  0.83773147]]



- 用`c_`进行按列堆叠

In [205]:
print(np.c_[np.r_[arr1, arr2], arr])
print()

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [-0.76291597  0.80553492  3.        ]
 [ 0.21346033  0.55389701  4.        ]
 [ 0.96813748  0.83773147  5.        ]]



- 利用切片将多个范围直接转为数组

In [206]:
np.c_[1:6, -5:0]

array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

- 使用`np.repeat`创建重复

In [207]:
arr = np.arange(3)
print(arr)

[0 1 2]


按元素重复

In [208]:
print(arr.repeat(3))

[0 0 0 1 1 1 2 2 2]


In [210]:
print(arr.repeat([2,3,5]))

[0 0 1 1 1 2 2 2 2 2]


指定axis来重复

In [211]:
arr = np.random.rand(2,2)
print(arr)

[[0.93109702 0.65424316]
 [0.76868321 0.01665136]]


In [212]:
print(arr.repeat(2, axis=0))

[[0.93109702 0.65424316]
 [0.93109702 0.65424316]
 [0.76868321 0.01665136]
 [0.76868321 0.01665136]]


In [213]:
print(arr.repeat(2, axis=1))

[[0.93109702 0.93109702 0.65424316 0.65424316]
 [0.76868321 0.76868321 0.01665136 0.01665136]]


- 还有Tile操作，具体的可参考
[numpy tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [214]:
print(arr)
print()
print(np.tile(arr, 2))

[[0.93109702 0.65424316]
 [0.76868321 0.01665136]]

[[0.93109702 0.65424316 0.93109702 0.65424316]
 [0.76868321 0.01665136 0.76868321 0.01665136]]


In [215]:
print(np.tile(arr, (2,3)))

[[0.93109702 0.65424316 0.93109702 0.65424316 0.93109702 0.65424316]
 [0.76868321 0.01665136 0.76868321 0.01665136 0.76868321 0.01665136]
 [0.93109702 0.65424316 0.93109702 0.65424316 0.93109702 0.65424316]
 [0.76868321 0.01665136 0.76868321 0.01665136 0.76868321 0.01665136]]


## 5. numpy文件输入/输出

- 读取csv文件作为数组

In [216]:
!head array_ex.txt

0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428
-1.484413,0.004176,-0.744203,0.005487
2.302869,0.200131,1.670238,-1.881090
-0.193230,1.047233,0.482803,0.960334


In [217]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
print(arr)

[[ 0.580052  0.18673   1.040717  1.134411]
 [ 0.194163 -0.636917 -0.938659  0.124094]
 [-0.12641   0.268607 -0.695724  0.047428]
 [-1.484413  0.004176 -0.744203  0.005487]
 [ 2.302869  0.200131  1.670238 -1.88109 ]
 [-0.19323   1.047233  0.482803  0.960334]]


- 数组文件读写

In [218]:
arr = np.arange(50).reshape(2,5,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
np.save('some_array', arr)

In [ ]:
arr2 = np.load('some_array.npy')
print(arr2)

多个数组可以一起压缩存储

In [219]:
arr3 = np.arange(15).reshape(3,5)
np.savez("array_archive.npz", arr=arr, b=arr2, c=arr3)

In [220]:
arch = np.load('array_archive.npz')
print(arch['arr'])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [221]:
arch['b']

array([[-0.76291597,  0.80553492],
       [ 0.21346033,  0.55389701],
       [ 0.96813748,  0.83773147]])

In [222]:
arch['c']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])


## 6. 课堂作业

用numpy写一个[softmax](http://cs231n.github.io/linear-classify/#softmax)

- 计算exponential
- 按行求和
- 每一行都要除以计算的和

In [ ]:
m = np.random.rand(10,10) * 10 + 1000
print(m)

In [ ]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print(m_row_max, m_row_max.shape)

In [ ]:
m = m - m_row_max
print(m)

In [ ]:
m_exp = np.exp(m)
print(m_exp, m_exp.shape)

In [ ]:
m_exp_row_sum = m_exp.sum(axis=1).reshape(10,1)
print(m_exp_row_sum, m_exp_row_sum.shape)

In [ ]:
m_softmax = m_exp / m_exp_row_sum
print(m_softmax)

In [ ]:
print(m_softmax.sum(axis=1))

更多的numpy细节和用法可以查看一下官网[numpy指南](http://docs.scipy.org/doc/numpy/reference/)

In [ ]:
np.linalg