# 第八章B：NumPy基础
___

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- broadcasting
- 逻辑运算
- 数组高级操作
- 文件输入输出
- 随堂小项目：用Numpy写一个Softmax

## 1. Numpy简介

- [numpy](http://www.numpy.org/)是Python的一个包
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，其核心代码由C语言写成
- Pandas也是基于Numpy构建的一个包
- 流行的机器学习框架（Tensorflow/PyTorch等），语法都与Numpy比较接近

首先导入`numpy` 模块:

In [2]:
import numpy as np

## 2. 数组Array

通常我们把1维数组看作向量（vector），2维数组看做矩阵（matrix），3维以上数组看做张量（tensor）...

### 2.1 数组的初始化和访问、修改

- 我们可以用`np.array()`从list初始化一个数组:

In [11]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
type([1,2,3])

list

- 可以对数组的元素进行操作（访问和赋值）

In [14]:
a[2]

3

In [15]:
a[0] = 5

In [16]:
print(a)

[5 2 3]


- 这是二维数组-矩阵

In [17]:
b = np.array([[1,2,3], [2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [18]:
print(type(b))

<class 'numpy.ndarray'>


In [19]:
print(b.shape)

(2, 3)


In [20]:
print(b[0,2])

3


### 2.2 创建数组的内置函数

有一些内置的创建数组的函数:
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eyes()`
- `np.empty()`

In [21]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [23]:
c = np.full((2,2), 8)
print(c)

[[8 8]
 [8 8]]


In [24]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
f = np.empty((2,3,4))
print(f)

[[[6.90894691e-310 4.65750766e-310 2.40730476e-312 2.98233776e-308]
  [1.33360299e+241 1.54628975e+218 1.28549958e-308 2.05226943e-289]
  [4.02977523e-270 7.43362324e-251 1.37251951e-231 7.44726967e-251]]

 [[3.19711065e-241 4.03347230e-270 6.57888840e-222 9.36041872e-231]
  [2.75926406e-306 4.03914047e-270 2.76477115e-306 5.07929194e-299]
  [2.18254332e-289 5.08432724e-299 2.84234937e-269 7.77409979e-299]]]


In [26]:
print(f.shape)

(2, 3, 4)


- 还有用`np.random`模块构建随机数的方法：
   * `np.random.rand()`
   * `np.random.randint()`
   * `np.random.randn()`
   * `np.random.random()`
   * ...

In [5]:
e = np.random.random((3,2))
print(e)

[[0.1390798  0.94794025]
 [0.15363898 0.99470466]
 [0.29629988 0.92044736]]


- 常用的还有类似于`range`的函数`np.arange()`：

In [9]:
g = np.arange(15)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
print(g.shape)

(15,)


### 2.3 数组的数据类型

数组可以有不同的数据类型：

In [37]:
arr = np.array([1,2,3])
print(arr.dtype)

int32


In [38]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [39]:
arr

array([ 1.,  2.,  3.])

In [40]:
arr = np.array([1,2,3], dtype=np.int64)
print(arr.dtype)

int64


- 生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

- 使用`astype`复制数组并转换数据类型

In [27]:
int_arr = np.array([1,2,3,4,5])
print(int_arr, int_arr.dtype)

[1 2 3 4 5] int64


In [28]:
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

float64 [1. 2. 3. 4. 5.]


- 使用`astype`将`float`转换为`int`时小数部分被舍弃

In [29]:
float_arr = np.array([3.5,2.3,4.8,-2.2])
print(float_arr)

[ 3.5  2.3  4.8 -2.2]


In [30]:
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)

[ 3  2  4 -2] int64


- 使用`astype`把字符串数组转换为其他类型的数组，如果失败抛出异常。

In [35]:
str_arr = np.array(['1.24', '2.2', '5.8', '0x12ab'], dtype=np.string_)
str_arr

array([b'1.24', b'2.2', b'5.8', b'0x12ab'], dtype='|S6')

In [36]:
float_arr = str_arr.astype(dtype=np.float)
print(float_arr)

ValueError: could not convert string to float: '0x12ab'

- `astype`可以使用其它数组的数据类型作为参数

In [37]:
int_arr = np.arange(10)
float_arr = np.array([2.3,4.6,9.8])
print(float_arr.dtype, int_arr.dtype)

float64 int64


In [38]:
int_arr.astype(dtype=float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 2.4 数组取值和赋值Array indexing

Numpy提供了多种取值方式.

- 创建3x4的2维数组/矩阵

In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


- 可以像list一样切片（多维数组可以从各个维度同时切片）:

In [40]:
b = a[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


- 然后可以修改切片出来的对象，然后完成对原数组的赋值.

In [41]:
b[0,0] = 111111
print(b)
print(a)

[[111111      4]
 [     7      8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- 可以通过行列的索引获取你想要的部分数据:

In [42]:
row_r1 = a[1,:]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [43]:
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [44]:
row_r3 = a[[1], :]
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)


在第2个维度上切片也可以:

In [45]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [96]:
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


- 还可以自由地行列组合进行取值:

In [98]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
print(a[[0,1,2], [0,1,0]])
print(a[[0,1,2], [0,1,0]].shape)

[1 6 9]
(3,)


In [48]:
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 6 9]


In [49]:
print(a)
print(a[[0,0], [1,0]])
print(np.array([a[0,0], a[0,1]]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 1]
[1 2]


- 更多的时候，我们需要用条件判定取值:

In [50]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
bool_index = (a > 2)
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


- 用这个布尔数组作为下标就可以获取符合条件的元素

In [52]:
print(a[bool_index].shape)

(4,)


- 将几个操作合并到一起：

In [53]:
print(a[a>2])

[3 4 5 6]


## 3. 数学运算

下面这些运算在科学运算中经常经常会用到的。

### 3.1 逐个元素的运算

In [54]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [56]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [57]:
print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


- 逐个元素求和有下面2种方式
  * 用`<arr> + <arr>`
  * 用`np.add()`函数

In [58]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [59]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

- 还有逐个元素算差

In [60]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [61]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

- 逐元素相乘

In [62]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [63]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

- 逐元素相除

In [64]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [65]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

- 逐个元素求平方根：

In [130]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

### 3.2 矩阵的乘法

- 那矩阵的乘法运算怎么办？可以参考[matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html)

我们可以构造两个向量，求向量的内积也有两种方式：
- `<v1>.dot(<v2>)`
- `np.dot(<v1>, <v2>)`

In [66]:
v = np.array([9,10])
w = np.array([10,11])
print(v.shape)

(2,)


In [67]:
v.dot(w)

200

In [68]:
np.dot(v,w)

200

- 对于矩阵之间的乘法

In [69]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [70]:
v

array([ 9, 10])

In [71]:
print(x.dot(v))

[29 67]


In [72]:
np.dot(x, v)

array([29, 67])

In [73]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [74]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

- 矩阵的转置简单粗暴

In [75]:
x

array([[1, 2],
       [3, 4]])

In [76]:
x.T

array([[1, 3],
       [2, 4]])

- 一维的vector转置还是自己

In [77]:
v.shape

(2,)

In [78]:
v.T.shape

(2,)

- 二维的就不一样了

In [79]:
w = np.array([[1,2,3]])
print(w, w.shape)

[[1 2 3]] (1, 3)


In [80]:
print(w.T)

[[1]
 [2]
 [3]]


- 利用转置矩阵可以计算内积

In [81]:
arr = np.random.randn(6,3)
arr

array([[ 0.62341702,  2.24055289, -1.98242427],
       [ 0.34986681, -0.45824109, -1.34195576],
       [ 1.63885345, -0.41403202, -1.73438195],
       [ 0.28822343,  0.1349485 ,  1.60655983],
       [-0.14924503, -0.8012538 ,  0.43684105],
       [ 1.47507951, -0.22302143, -0.88134321]])

In [82]:
print(arr.T.dot(arr))

[[ 5.47810261  0.38744179 -5.44998015]
 [ 0.38744179  6.11144197 -3.04535679]
 [-5.44998015 -3.04535679 12.28756243]]


In [83]:
print(np.dot(arr,arr))

ValueError: shapes (6,3) and (6,3) not aligned: 3 (dim 1) != 6 (dim 0)

- 高维的tensor也可以转置

In [86]:
arr = np.arange(16).reshape(2,2,4)
print(arr, arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [87]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [88]:
print(arr.transpose((0,2,1)))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [89]:
print(arr.transpose((2,1,0)))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [90]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [91]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(x)
print()
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [92]:
print(np.matmul(x,y).shape)

(2, 3, 2)


In [93]:
print(np.dot(x,y).shape)

(2, 3, 2)


In [94]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(16).reshape(2,4,2)
print(x.dot(y).shape)

(2, 3, 2, 2)


In [95]:
np.matmul(x,y).shape

(2, 3, 2)

- 科学运算常用到的矩阵内元素的运算是求和，用 `np.sum()`就可以完成:

In [96]:
x= np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [97]:
print(np.sum(x))
print(x.sum())

10
10


In [98]:
print(np.sum(x, axis=0))

[4 6]


In [99]:
print(np.sum(x, axis=1))

[3 7]


In [100]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]


- 还有一些运算，如求和，求平均，求累和，累积都可以用`numpy`实现

In [101]:
print(x.cumsum(axis=0))
print(x.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [102]:
print(x.cumprod(axis=0))
print(x.cumprod(axis=1))

[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]


以上是最基本的运算，更多的运算可能得查查相关[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### 3.3 其他基本运算

- 比如一维数组的排序：

In [103]:
arr = np.random.randn(8) * 10
print(arr)

[17.19486487  5.20675039 -1.4273732  13.5430823   2.1223183   1.80617076
 12.05506747 -1.14126762]


In [104]:
arr.sort()
print(arr)

[-1.4273732  -1.14126762  1.80617076  2.1223183   5.20675039 12.05506747
 13.5430823  17.19486487]


- 二维数组也可以在某些维度上排序

In [105]:
arr = np.random.randn(5,3) * 10
print(arr)

[[  2.6185086   14.91674349   3.64798981]
 [ -4.24692423   8.31100487  -0.11665075]
 [ -6.06940092  -0.67864685 -10.26205463]
 [ -7.23787695  -0.85135467 -18.45461562]
 [  5.08369863   0.48543606  -0.20827203]]


In [106]:
arr.sort(1)
print(arr)

[[  2.6185086    3.64798981  14.91674349]
 [ -4.24692423  -0.11665075   8.31100487]
 [-10.26205463  -6.06940092  -0.67864685]
 [-18.45461562  -7.23787695  -0.85135467]
 [ -0.20827203   0.48543606   5.08369863]]


- 我们可以很容易找出排序后位置在5%的数字

In [193]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05 * len(large_arr))])

-1.71556330464


### 3.4 广播Broadcasting

> 当一个小矩阵去与大矩阵进行运算的时候，我们希望小矩阵能循环和大矩阵的块进行相同的计算，这就需要用到广播了。

- 比如，给矩阵x的每一行都逐元素加上一个向量，然后生成y

In [107]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print()
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]


In [108]:
y = np.empty_like(x)
print(y)

[[139838642260072 139838642260072               0]
 [              0               0               0]
 [              0               0               0]
 [              0               0               0]]


- 一种比较简暴的方式是，用for循环逐个相加

In [109]:
for i in range(4):
    y[i,:] = x[i,:] + v    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


- 这种方法当然可以，问题是效率低下，尤其是当x矩阵的行数非常多的情况。

> Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

- 正因为broadcasting机制的存在，上面的操作可以简化为一个简单的求和操作：

In [110]:
print(x.shape, v.shape)
x + v

(4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，如果两arrays兼容，则输出broadcasting结果：

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):          3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):     1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [201]:
v = np.array([1,2,3])
w = np.array([4,5])
print(v.shape, w.shape)

(3,) (2,)


In [203]:
v = v.reshape(3,1)
print(v.shape)

(3, 1)


In [204]:
v + w

array([[5, 6],
       [6, 7],
       [7, 8]])

那如果要把一个矩阵的每一行都加上一个向量呢

In [205]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [206]:

x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5]) # 2

In [211]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

上面那个操作太复杂了，其实我们可以直接这么做嘛

In [212]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

broadcasting当然可以逐元素运算了

总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

### 3.5 逻辑运算

In [213]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [214]:
cond = np.array([True, False, True, True, False])

In [215]:
print(np.where(cond, x_arr, y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [216]:
arr = np.random.randn(4,4)
print(arr)

[[ 0.94534017  0.04955986  0.20184702  0.40272432]
 [-0.20872753 -0.04952711  0.0059752  -1.9356753 ]
 [ 1.20042485 -0.92834374  1.57810979 -0.96378859]
 [-2.09492281 -0.38678213 -0.67656147  1.45629059]]


In [217]:
arr > 0

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False, False, False,  True]], dtype=bool)

In [218]:
print(np.where(arr > 0, 1,-1))

[[ 1  1  1  1]
 [-1 -1  1 -1]
 [ 1 -1  1 -1]
 [-1 -1 -1  1]]


In [219]:
print(np.where(arr > 0, 1,arr))

[[ 1.          1.          1.          1.        ]
 [-0.20872753 -0.04952711  1.         -1.9356753 ]
 [ 1.         -0.92834374  1.         -0.96378859]
 [-2.09492281 -0.38678213 -0.67656147  1.        ]]


## 4. 高级的ndarray操作

### 4.1 用reshape来改变tensor的形状

numpy可以很容易地把一维数组转成二维数组，三维数组。

In [111]:
arr = np.arange(8)
print(arr.shape)

(8,)


In [112]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [113]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [114]:
arr = np.arange(15)
print(arr.reshape(5,3).shape)

(5, 3)


如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度

In [229]:
print(arr.reshape(5,-1).shape)

(5, 3)


还可以从其他的ndarray中获取shape信息然后reshape

In [117]:
other_arr = np.ones((3,5))
print(other_arr.shape) # tuple

(3, 5)


In [118]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用ravel来拉平

In [119]:
arr = arr.reshape(other_arr.shape)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [120]:
arr.ravel().shape

(15,)

### 4.2 连接两个二维数组

In [123]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1, "\n\n", arr2)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]]


In [124]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [125]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- 还有所谓的堆叠（stack）。堆叠是连接的另一种表述
- 堆叠还可以分为垂直stack与水平stack

In [126]:
np.vstack((arr1, arr2)) # vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [127]:
np.hstack((arr1, arr2)) # horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- 还可以拆分数组

In [128]:
arr = np.random.rand(5,5)
print(arr)

[[0.80654058 0.4867738  0.47972881 0.2431     0.37442823]
 [0.31897448 0.02200435 0.75737596 0.29367908 0.40327294]
 [0.06636673 0.39065749 0.73313092 0.70968976 0.43371828]
 [0.18976501 0.57902178 0.39880978 0.49977996 0.30288202]
 [0.6425076  0.52059581 0.38005411 0.34862574 0.93999701]]


In [129]:
first, second, third = np.split(arr, [1,3], axis=0)
print(first, '\n\n', second, '\n\n', third)

[[0.80654058 0.4867738  0.47972881 0.2431     0.37442823]] 

 [[0.31897448 0.02200435 0.75737596 0.29367908 0.40327294]
 [0.06636673 0.39065749 0.73313092 0.70968976 0.43371828]] 

 [[0.18976501 0.57902178 0.39880978 0.49977996 0.30288202]
 [0.6425076  0.52059581 0.38005411 0.34862574 0.93999701]]


- 堆叠辅助

In [130]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
[[-1.73551655  0.1420043 ]
 [-1.29334955 -0.00579216]
 [-0.34209179 -1.1680922 ]]


- 还可以用`np.r_()`按行堆叠

In [258]:
print(np.r_[arr1, arr2])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [-0.60392123 -0.1769936 ]
 [ 0.46523138  0.71963034]
 [-0.51733042  1.50108329]]



- 用`c_`进行按列堆叠

In [259]:
print(np.c_[np.r_[arr1, arr2], arr])
print()

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [-0.60392123 -0.1769936   3.        ]
 [ 0.46523138  0.71963034  4.        ]
 [-0.51733042  1.50108329  5.        ]]



- 利用切片将多个范围直接转为数组

In [260]:
np.c_[1:6, -5:0]

array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

- 使用`np.repeat`创建重复

In [131]:
arr = np.arange(3)
print(arr)

[0 1 2]


按元素重复

In [132]:
print(arr.repeat(3))

[0 0 0 1 1 1 2 2 2]


In [263]:
print(arr.repeat([2,3,5]))

[0 0 1 1 1 2 2 2 2 2]


指定axis来重复

In [133]:
arr = np.random.rand(2,2)
print(arr)

[[0.51108926 0.32633807]
 [0.79179806 0.26604535]]


In [134]:
print(arr.repeat(2, axis=0))

[[0.51108926 0.32633807]
 [0.51108926 0.32633807]
 [0.79179806 0.26604535]
 [0.79179806 0.26604535]]


In [266]:
print(arr.repeat(2, axis=1))

[[ 0.90063544  0.90063544  0.36862431  0.36862431  0.46734451  0.46734451]
 [ 0.61467785  0.61467785  0.63962631  0.63962631  0.61288228  0.61288228]]


- 还有Tile操作，具体的可参考
[numpy tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [135]:
print(arr)
print()
print(np.tile(arr, 2))

[[0.51108926 0.32633807]
 [0.79179806 0.26604535]]

[[0.51108926 0.32633807 0.51108926 0.32633807]
 [0.79179806 0.26604535 0.79179806 0.26604535]]


In [136]:
print(np.tile(arr, (2,3)))

[[0.51108926 0.32633807 0.51108926 0.32633807 0.51108926 0.32633807]
 [0.79179806 0.26604535 0.79179806 0.26604535 0.79179806 0.26604535]
 [0.51108926 0.32633807 0.51108926 0.32633807 0.51108926 0.32633807]
 [0.79179806 0.26604535 0.79179806 0.26604535 0.79179806 0.26604535]]


## 5. numpy文件输入/输出

- 读取csv文件作为数组

In [138]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
print(arr)

[[ 0.580052  0.18673   1.040717  1.134411]
 [ 0.194163 -0.636917 -0.938659  0.124094]
 [-0.12641   0.268607 -0.695724  0.047428]
 [-1.484413  0.004176 -0.744203  0.005487]
 [ 2.302869  0.200131  1.670238 -1.88109 ]
 [-0.19323   1.047233  0.482803  0.960334]]


- 数组文件读写

In [139]:
arr = np.arange(50).reshape(2,5,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [140]:
np.save('some_array', arr)

In [141]:
arr2 = np.load('some_array.npy')
print(arr2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


多个数组可以一起压缩存储

In [142]:
arr3 = np.arange(15).reshape(3,5)
np.savez("array_archive.npz", arr=arr, b=arr2, c=arr3)

In [143]:
arch = np.load('array_archive.npz')
print(arch['arr'])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [144]:
arch['b']

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [145]:
arch['c']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])


## 6. 课堂作业

用numpy写一个[softmax](http://cs231n.github.io/linear-classify/#softmax)

- 计算exponential
- 按行求和
- 每一行都要除以计算的和

In [294]:
m = np.random.rand(10,10) * 10 + 1000
print(m)

[[ 1008.64304012  1001.25079229  1006.81896868  1005.89015258  1008.8915297
   1001.84923866  1005.53509734  1005.34075305  1008.93404709
   1006.94897664]
 [ 1003.24267825  1003.72710741  1000.28354398  1000.32012105  1004.3690361
   1007.18390602  1002.49741606  1005.83510332  1009.19678396
   1002.32098566]
 [ 1002.32824002  1006.2813999   1009.27645662  1002.57259159
   1006.30743627  1000.35201323  1003.94430099  1008.79056869
   1007.40485841  1006.38239542]
 [ 1007.06228714  1006.01325352  1007.96901864  1002.34269542
   1000.75563221  1005.26357317  1006.14861174  1005.68119044
   1000.69006453  1007.21834125]
 [ 1004.15770428  1003.0554848   1005.55619032  1003.04000025
   1005.54338468  1002.23952638  1008.86317857  1006.96983789
   1005.84232318  1009.28833837]
 [ 1008.47151667  1006.30354927  1006.69274016  1004.12418543
   1007.17550972  1004.31758292  1007.27760499  1007.45250445
   1000.02943239  1002.25886446]
 [ 1000.63764781  1003.39894276  1008.26298759  1001.8929501

In [295]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print(m_row_max, m_row_max.shape)

[[ 1008.93404709]
 [ 1009.19678396]
 [ 1009.27645662]
 [ 1007.96901864]
 [ 1009.28833837]
 [ 1008.47151667]
 [ 1008.26298759]
 [ 1009.57634418]
 [ 1008.73282377]
 [ 1009.56831564]] (10, 1)


In [296]:
m = m - m_row_max
print(m)

[[-0.29100696 -7.6832548  -2.11507841 -3.04389451 -0.04251738 -7.08480843
  -3.39894975 -3.59329403  0.         -1.98507045]
 [-5.95410571 -5.46967655 -8.91323998 -8.87666291 -4.82774786 -2.01287794
  -6.6993679  -3.36168065  0.         -6.8757983 ]
 [-6.9482166  -2.99505673  0.         -6.70386503 -2.96902035 -8.9244434
  -5.33215563 -0.48588793 -1.87159821 -2.8940612 ]
 [-0.9067315  -1.95576512  0.         -5.62632322 -7.21338643 -2.70544547
  -1.82040689 -2.2878282  -7.27895411 -0.75067739]
 [-5.13063409 -6.23285357 -3.73214805 -6.24833812 -3.74495369 -7.04881199
  -0.4251598  -2.31850048 -3.44601518  0.        ]
 [ 0.         -2.16796739 -1.77877651 -4.34733123 -1.29600694 -4.15393374
  -1.19391168 -1.01901222 -8.44208427 -6.21265221]
 [-7.62533977 -4.86404483  0.         -6.37003747 -0.4091039  -3.58733504
  -3.67426051 -5.01809944 -7.86769844 -1.05334294]
 [-4.3581911  -2.14983063 -3.25226701 -6.56671127 -4.54088515 -0.71708981
   0.         -5.83088393 -6.1712155  -5.13258358]
 

In [297]:
m_exp = np.exp(m)
print(m_exp, m_exp.shape)

[[  7.47510474e-01   4.60473707e-04   1.20623832e-01   4.76489585e-02
    9.58373807e-01   8.37735258e-04   3.34083387e-02   2.75075701e-02
    1.00000000e+00   1.37370936e-01]
 [  2.59516363e-03   4.21259451e-03   1.34595041e-04   1.39609277e-04
    8.00452828e-03   1.33603617e-01   1.23169021e-03   3.46769303e-02
    1.00000000e+00   1.03247308e-03]
 [  9.60346309e-04   5.00337887e-02   1.00000000e+00   1.22616357e-03
    5.13535942e-02   1.33095533e-04   4.83363924e-03   6.15150742e-01
    1.53877536e-01   5.53509641e-02]
 [  4.03842028e-01   1.41456204e-01   1.00000000e+00   3.60179403e-03
    7.36658284e-04   6.68405420e-02   1.61959837e-01   1.01486632e-01
    6.89906753e-04   4.72046684e-01]
 [  5.91281003e-03   1.96383995e-03   2.39413532e-02   1.93366498e-03
    2.36367236e-02   8.68440058e-04   6.53665320e-01   9.84210597e-02
    3.18723893e-02   1.00000000e+00]
 [  1.00000000e+00   1.14409931e-01   1.68844601e-01   1.29413038e-02
    2.73622203e-01   1.57025251e-02   3.03033

In [298]:
m_exp_row_sum = m_exp.sum(axis=1).reshape(10,1)
print(m_exp_row_sum, m_exp_row_sum.shape)

[[ 3.07374213]
 [ 1.1856312 ]
 [ 1.93291987]
 [ 2.35266029]
 [ 1.8422156 ]
 [ 2.25172496]
 [ 2.08297446]
 [ 1.67915853]
 [ 2.6135361 ]
 [ 2.73515418]] (10, 1)


In [299]:
m_softmax = m_exp / m_exp_row_sum
print(m_softmax)

[[  2.43192319e-01   1.49808829e-04   3.92433154e-02   1.55019376e-02
    3.11793823e-01   2.72545719e-04   1.08689465e-02   8.94921207e-03
    3.25336336e-01   4.46917571e-02]
 [  2.18884559e-03   3.55303952e-03   1.13521845e-04   1.17751015e-04
    6.75128005e-03   1.12685645e-01   1.03884767e-03   2.92476533e-02
    8.43432594e-01   8.70821452e-04]
 [  4.96837103e-04   2.58850817e-02   5.17352020e-01   6.34358200e-04
    2.65678857e-02   6.88572427e-05   2.50069303e-03   3.18249479e-01
    7.96088542e-02   2.86359331e-02]
 [  1.71653353e-01   6.01260646e-02   4.25050742e-01   1.53094522e-03
    3.13117150e-04   2.84106220e-02   6.88411489e-02   4.31369681e-02
    2.93245377e-04   2.00643793e-01]
 [  3.20961891e-03   1.06602069e-03   1.29959562e-02   1.04964098e-03
    1.28305957e-02   4.71410652e-04   3.54825635e-01   5.34253752e-02
    1.73011179e-02   5.42824629e-01]
 [  4.44103973e-01   5.08099049e-02   7.49845582e-02   5.74728445e-03
    1.21516707e-01   6.97355379e-03   1.34578

In [300]:
print(m_softmax.sum(axis=1))

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


更多的numpy细节和用法可以查看一下官网[numpy指南](http://docs.scipy.org/doc/numpy/reference/)